/*  Message-number definitions derived from "ELWWHO.MSG"  */

#define SHOWLON     1
#define WHICHLST    2
#define GLOCHR      3
#define FILTER1     4
#define FILTER2     5
#define FILTER3     6
#define FILTER4     7
#define FILTER5     8
#define WHOHELP    10
#define LISTHDR1   11
#define LISTHDR2   12
#define LISTHDR3   13
#define LISTHDR4   14
#define LISTLIN1   15
#define LISTLIN2   16
#define LISTLIN3   17
#define LISTLIN4   18
#define LISTFTR1   19
#define LISTFTR2   20
#define LISTFTR3   21
#define LISTFTR4   22
#define NOFILTER   23
